CREATE TABLE CATALOG
(
	CATALOGUE_ID      NUMBER,
	CATALOGUE_NAME    VARCHAR2(100) NOT NULL,
	DESCRR            VARCHAR2(250),
	CONSTRAINT  CATALOGUE_PK PRIMARY KEY(CATALOGUE_ID)
);

CREATE SEQUENCE  CATALOGUE_S
   INCREMENT BY 1
   START WITH 1
   MAXVALUE 999999999999999
   NOCACHE
   NOCYCLE
   ;


INSERT INTO CATALOGUE(CATALOGUE_ID,CATALOGUE_NAME,DESCRR) VALUES(101,'INFORMATION TECHNOLOGGY','IT DESCRription');
INSERT INTO CATALOGUE(CATALOGUE_ID,CATALOGUE_NAME,DESCRR) VALUES(102,'DIAGNOSTICS','Diagnostics DESCRription');
INSERT INTO CATALOGUE(CATALOGUE_ID,CATALOGUE_NAME,DESCRR) VALUES(103,'LABORATRY','Laboratry DESCRription');
INSERT INTO CATALOGUE(CATALOGUE_ID,CATALOGUE_NAME,DESCRR) VALUES(104,'MEDICIENS','Mediciens DESCRription');



CREATE TABLE CATEGORY
(
	CATEGORY_ID     NUMBER PRIMARY KEY,
	CATALOGUE_ID    NUMBER,
	CATEGORY_NAME   VARCHAR2(30) NOT NULL,
	DESCR           VARCHAR2(250)
);

CREATE SEQUENCE  CATEGORY_S
   INCREMENT BY 1
   START WITH 1
   MAXVALUE 999999999999999
   NOCACHE
   NOCYCLE
   ;

INSERT INTO  CATEGORY(CATALOGUE_ID,CATEGORY_ID,CATEGORY_NAME,DESCR) VALUES(101,501,'NOTEBOOKS','Notebook DESCRription');
INSERT INTO  CATEGORY(CATALOGUE_ID,CATEGORY_ID,CATEGORY_NAME,DESCR) VALUES(101,502,'PRINTERS','Printer DESCRription');
INSERT INTO  CATEGORY(CATALOGUE_ID,CATEGORY_ID,CATEGORY_NAME,DESCR) VALUES(104,503,'MALERIA',' Maleria Medicien DESCRription');
INSERT INTO  CATEGORY(CATALOGUE_ID,CATEGORY_ID,CATEGORY_NAME,DESCR) VALUES(104,504,'CANCER',' Cancer Medicien DESCRription');


CREATE TABLE ITEM
(
	PRODUCT_CODE    VARCHAR2(30),
	CATEGORY_ID     NUMBER,	
	DESCR           VARCHAR2(250),
	UOM             VARCHAR2(30),
	UNIT_PRICE      NUMBER(30) NOT NULL,
	CURRENCY	VARCHAR2(4) NOT NULL,
	MANUFACTURER	VARCHAR2(50),
	MODE_OF_PAY	VARCHAR2(15),
	CONSTRAINT      ITEM_PK  PRIMARY KEY(PRODUCT_CODE) 
);

INSERT INTO ITEM(CATEGORY_ID,PRODUCT_CODE,UOM,UNIT_PRICE,CURRENCY,MODE_OF_PAY) VALUES('501','HPPallivion6700','Each',800,'USD','AIR');
INSERT INTO ITEM(CATEGORY_ID,PRODUCT_CODE,UOM,UNIT_PRICE,CURRENCY,MODE_OF_PAY) VALUES('501','HPPallivion9500','Each',700,'USD','AIR');
INSERT INTO ITEM(CATEGORY_ID,PRODUCT_CODE,UOM,UNIT_PRICE,CURRENCY,MODE_OF_PAY) VALUES('502','Canon 70X','Each',80,'USD','AIR');
INSERT INTO ITEM(CATEGORY_ID,PRODUCT_CODE,UOM,UNIT_PRICE,CURRENCY,MODE_OF_PAY) VALUES('502','HP Xi','Each',70,'USD','AIR');
INSERT INTO ITEM(CATEGORY_ID,PRODUCT_CODE,UOM,UNIT_PRICE,CURRENCY,MODE_OF_PAY) VALUES('503','PROPHYLACTIC','Each',1,'USD','SURFACE');



CREATE TABLE PFI_DETAILS
(
	MODE_OF_PAY  VARCHAR2(15),
	PFI_PER	     NUMBER
);

INSERT INTO PFI_DETAILS(MODE_OF_PAY,PFI_PER) VALUES('AIR',11.5);
INSERT INTO PFI_DETAILS(MODE_OF_PAY,PFI_PER) VALUES('SURFACE',9);
	

CREATE TABLE REGISTRATION
(
	REGISTRATION_ID		NUMBER,
	REG_NUM			VARCHAR2(30),
	PROC_TYPE		VARCHAR2(30),
	REG_STATUS		VARCHAR2(30),
	TOTAL_USD_AMT		NUMBER(30,3),
	TOTAL_PFI_AMT		NUMBER(30,3),
	REQUESTED_BY		NUMBER(6),
	URGENCY			VARCHAR2(30),
	CONSIGNEE_ID            NUMBER(6),
	SHIPING_ID		NUMBER(6),
	Notes_BUYER		VARCHAR2(100),
	PARTY_NOTES		VARCHAR2(100),
	CREATED_BY		NUMBER(6),
	CREATION_DATE		DATE,
	LAST_UPDATED_BY		NUMBER(15),
	CONSTRAINT		REGISTRATION_ID  PRIMARY KEY(REGISTRATION_ID)
);

CREATE SEQUENCE  REGISTRATION_S
   INCREMENT BY 1
   START WITH 1
   MAXVALUE 999999999999999
   NOCACHE
   NOCYCLE
   ;


CREATE TABLE REGISTRATION_LINES
(
	REGISTRATION_ID		NUMBER,
	LINE_ID			NUMBER,
	PRODUCT_CODE		VARCHAR2(30),
	QTY			NUMBER(15),
	CONSTRAINT CATEGORY_PK  PRIMARY KEY(LINE_ID) 
);

CREATE SEQUENCE  REGISTRATION_LINES_S
   INCREMENT BY 1
   START WITH 1
   MAXVALUE 999999999999999
   NOCACHE
   NOCYCLE
   ;

commit;