package model.client;

import model.common.MyLearningAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 08 12:19:10 IST 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MyLearningAMClient extends ApplicationModuleImpl implements MyLearningAM {
    /**
     * This is the default constructor (do not remove).
     */
    public MyLearningAMClient() {
    }

    public void getItemInCategory() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getItemInCategory",null,null);
        return;
    }


    public void getItemInCategory(String CategoryId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getItemInCategory",new String [] {"java.lang.String"},new Object[] {CategoryId});
        return;
    }

    public void initilizeNewRegLines(String productCode, String regId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"initilizeNewRegLines",new String [] {"java.lang.String","java.lang.String"},new Object[] {productCode, regId});
        return;
    }

    public void updateRegLinesAmt() {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateRegLinesAmt",null,null);
        return;
    }
}
