package model.view;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 08 12:15:54 IST 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CategoryVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CategoryId {
            public Object get(CategoryVORowImpl obj) {
                return obj.getCategoryId();
            }

            public void put(CategoryVORowImpl obj, Object value) {
                obj.setCategoryId((Number)value);
            }
        }
        ,
        CatalogueId {
            public Object get(CategoryVORowImpl obj) {
                return obj.getCatalogueId();
            }

            public void put(CategoryVORowImpl obj, Object value) {
                obj.setCatalogueId((Number)value);
            }
        }
        ,
        CategoryName {
            public Object get(CategoryVORowImpl obj) {
                return obj.getCategoryName();
            }

            public void put(CategoryVORowImpl obj, Object value) {
                obj.setCategoryName((String)value);
            }
        }
        ,
        Descr {
            public Object get(CategoryVORowImpl obj) {
                return obj.getDescr();
            }

            public void put(CategoryVORowImpl obj, Object value) {
                obj.setDescr((String)value);
            }
        }
        ,
        ItemListPageVO {
            public Object get(CategoryVORowImpl obj) {
                return obj.getItemListPageVO();
            }

            public void put(CategoryVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(CategoryVORowImpl object);

        public abstract void put(CategoryVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int CATALOGUEID = AttributesEnum.CatalogueId.index();
    public static final int CATEGORYNAME = AttributesEnum.CategoryName.index();
    public static final int DESCR = AttributesEnum.Descr.index();
    public static final int ITEMLISTPAGEVO = AttributesEnum.ItemListPageVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CategoryVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryId.
     * @return the CategoryId
     */
    public Number getCategoryId() {
        return (Number) getAttributeInternal(CATEGORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryId.
     * @param value value to set the  CategoryId
     */
    public void setCategoryId(Number value) {
        setAttributeInternal(CATEGORYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CatalogueId.
     * @return the CatalogueId
     */
    public Number getCatalogueId() {
        return (Number) getAttributeInternal(CATALOGUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CatalogueId.
     * @param value value to set the  CatalogueId
     */
    public void setCatalogueId(Number value) {
        setAttributeInternal(CATALOGUEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryName.
     * @return the CategoryName
     */
    public String getCategoryName() {
        return (String) getAttributeInternal(CATEGORYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryName.
     * @param value value to set the  CategoryName
     */
    public void setCategoryName(String value) {
        setAttributeInternal(CATEGORYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Descr.
     * @return the Descr
     */
    public String getDescr() {
        return (String) getAttributeInternal(DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Descr.
     * @param value value to set the  Descr
     */
    public void setDescr(String value) {
        setAttributeInternal(DESCR, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ItemListPageVO.
     */
    public RowIterator getItemListPageVO() {
        return (RowIterator)getAttributeInternal(ITEMLISTPAGEVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * Sample exportable method.
     */
    public void sampleCategoryVORowImplExportable() {
    }

    /**
     * Sample exportable method.
     */
    public void sampleCategoryVORowImplExportable2(String testParam1) {
    }
}
