package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 08 12:15:38 IST 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CategoryVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CategoryVOImpl() {
    }
}
