package model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 20 17:36:59 IST 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ProductCode {
            public Object get(ItemVORowImpl obj) {
                return obj.getProductCode();
            }

            public void put(ItemVORowImpl obj, Object value) {
                obj.setProductCode((String)value);
            }
        }
        ,
        CategoryId {
            public Object get(ItemVORowImpl obj) {
                return obj.getCategoryId();
            }

            public void put(ItemVORowImpl obj, Object value) {
                obj.setCategoryId((Number)value);
            }
        }
        ,
        Descr {
            public Object get(ItemVORowImpl obj) {
                return obj.getDescr();
            }

            public void put(ItemVORowImpl obj, Object value) {
                obj.setDescr((String)value);
            }
        }
        ,
        Uom {
            public Object get(ItemVORowImpl obj) {
                return obj.getUom();
            }

            public void put(ItemVORowImpl obj, Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        UnitPrice {
            public Object get(ItemVORowImpl obj) {
                return obj.getUnitPrice();
            }

            public void put(ItemVORowImpl obj, Object value) {
                obj.setUnitPrice((Number)value);
            }
        }
        ,
        Currency {
            public Object get(ItemVORowImpl obj) {
                return obj.getCurrency();
            }

            public void put(ItemVORowImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        Manufacturer {
            public Object get(ItemVORowImpl obj) {
                return obj.getManufacturer();
            }

            public void put(ItemVORowImpl obj, Object value) {
                obj.setManufacturer((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ItemVORowImpl object);

        public abstract void put(ItemVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PRODUCTCODE = AttributesEnum.ProductCode.index();
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int DESCR = AttributesEnum.Descr.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int MANUFACTURER = AttributesEnum.Manufacturer.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ItemVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ProductCode.
     * @return the ProductCode
     */
    public String getProductCode() {
        return (String) getAttributeInternal(PRODUCTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductCode.
     * @param value value to set the  ProductCode
     */
    public void setProductCode(String value) {
        setAttributeInternal(PRODUCTCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryId.
     * @return the CategoryId
     */
    public Number getCategoryId() {
        return (Number) getAttributeInternal(CATEGORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryId.
     * @param value value to set the  CategoryId
     */
    public void setCategoryId(Number value) {
        setAttributeInternal(CATEGORYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Descr.
     * @return the Descr
     */
    public String getDescr() {
        return (String) getAttributeInternal(DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Descr.
     * @param value value to set the  Descr
     */
    public void setDescr(String value) {
        setAttributeInternal(DESCR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Uom.
     * @param value value to set the  Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UnitPrice.
     * @return the UnitPrice
     */
    public Number getUnitPrice() {
        return (Number) getAttributeInternal(UNITPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UnitPrice.
     * @param value value to set the  UnitPrice
     */
    public void setUnitPrice(Number value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Currency.
     * @param value value to set the  Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Manufacturer.
     * @return the Manufacturer
     */
    public String getManufacturer() {
        return (String) getAttributeInternal(MANUFACTURER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Manufacturer.
     * @param value value to set the  Manufacturer
     */
    public void setManufacturer(String value) {
        setAttributeInternal(MANUFACTURER, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * Sample exportable method.
     */
    public void sampleItemVORowImplExportable() {
    }

    /**
     * Sample exportable method.
     */
    public void sampleItemVORowImplExportable2(String testParam1) {
    }
}
