package model.view;

import model.entity.RegistrationEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 03 10:25:04 IST 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegistrationVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ConsigneeId {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getConsigneeId();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setConsigneeId((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        NotesBuyer {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getNotesBuyer();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setNotesBuyer((String)value);
            }
        }
        ,
        PartyNotes {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getPartyNotes();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setPartyNotes((String)value);
            }
        }
        ,
        ProcType {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getProcType();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setProcType((String)value);
            }
        }
        ,
        RegNum {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getRegNum();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setRegNum((String)value);
            }
        }
        ,
        RegStatus {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getRegStatus();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setRegStatus((String)value);
            }
        }
        ,
        RegistrationId {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getRegistrationId();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setRegistrationId((Number)value);
            }
        }
        ,
        RequestedBy {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getRequestedBy();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setRequestedBy((Number)value);
            }
        }
        ,
        ShipingId {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getShipingId();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setShipingId((Number)value);
            }
        }
        ,
        TotalPfiAmt {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getTotalPfiAmt();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setTotalPfiAmt((Number)value);
            }
        }
        ,
        TotalUsdAmt {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getTotalUsdAmt();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setTotalUsdAmt((Number)value);
            }
        }
        ,
        Urgency {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getUrgency();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setUrgency((String)value);
            }
        }
        ,
        LastUpadtedName {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getLastUpadtedName();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setLastUpadtedName((String)value);
            }
        }
        ,
        CreatedByName {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getCreatedByName();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setCreatedByName((String)value);
            }
        }
        ,
        ConsigneeName {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getConsigneeName();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setConsigneeName((String)value);
            }
        }
        ,
        ShippingName {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getShippingName();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setShippingName((String)value);
            }
        }
        ,
        RequestedByName {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getRequestedByName();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setRequestedByName((String)value);
            }
        }
        ,
        DepartmentName {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getDepartmentName();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setDepartmentName((String)value);
            }
        }
        ,
        RegistrationLinesVO {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getRegistrationLinesVO();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemDetailsVO {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getItemDetailsVO();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EmployeesVO1 {
            public Object get(RegistrationVORowImpl obj) {
                return obj.getEmployeesVO1();
            }

            public void put(RegistrationVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(RegistrationVORowImpl object);

        public abstract void put(RegistrationVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CONSIGNEEID = AttributesEnum.ConsigneeId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int NOTESBUYER = AttributesEnum.NotesBuyer.index();
    public static final int PARTYNOTES = AttributesEnum.PartyNotes.index();
    public static final int PROCTYPE = AttributesEnum.ProcType.index();
    public static final int REGNUM = AttributesEnum.RegNum.index();
    public static final int REGSTATUS = AttributesEnum.RegStatus.index();
    public static final int REGISTRATIONID = AttributesEnum.RegistrationId.index();
    public static final int REQUESTEDBY = AttributesEnum.RequestedBy.index();
    public static final int SHIPINGID = AttributesEnum.ShipingId.index();
    public static final int TOTALPFIAMT = AttributesEnum.TotalPfiAmt.index();
    public static final int TOTALUSDAMT = AttributesEnum.TotalUsdAmt.index();
    public static final int URGENCY = AttributesEnum.Urgency.index();
    public static final int LASTUPADTEDNAME = AttributesEnum.LastUpadtedName.index();
    public static final int CREATEDBYNAME = AttributesEnum.CreatedByName.index();
    public static final int CONSIGNEENAME = AttributesEnum.ConsigneeName.index();
    public static final int SHIPPINGNAME = AttributesEnum.ShippingName.index();
    public static final int REQUESTEDBYNAME = AttributesEnum.RequestedByName.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int REGISTRATIONLINESVO = AttributesEnum.RegistrationLinesVO.index();
    public static final int ITEMDETAILSVO = AttributesEnum.ItemDetailsVO.index();
    public static final int EMPLOYEESVO1 = AttributesEnum.EmployeesVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RegistrationVORowImpl() {
    }

    /**
     * Gets RegistrationEO entity object.
     * @return the RegistrationEO
     */
    public RegistrationEOImpl getRegistrationEO() {
        return (RegistrationEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CONSIGNEE_ID using the alias name ConsigneeId.
     * @return the CONSIGNEE_ID
     */
    public Number getConsigneeId() {
        return (Number) getAttributeInternal(CONSIGNEEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONSIGNEE_ID using the alias name ConsigneeId.
     * @param value value to set the CONSIGNEE_ID
     */
    public void setConsigneeId(Number value) {
        setAttributeInternal(CONSIGNEEID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for NOTES_BUYER using the alias name NotesBuyer.
     * @return the NOTES_BUYER
     */
    public String getNotesBuyer() {
        return (String) getAttributeInternal(NOTESBUYER);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTES_BUYER using the alias name NotesBuyer.
     * @param value value to set the NOTES_BUYER
     */
    public void setNotesBuyer(String value) {
        setAttributeInternal(NOTESBUYER, value);
    }

    /**
     * Gets the attribute value for PARTY_NOTES using the alias name PartyNotes.
     * @return the PARTY_NOTES
     */
    public String getPartyNotes() {
        return (String) getAttributeInternal(PARTYNOTES);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTY_NOTES using the alias name PartyNotes.
     * @param value value to set the PARTY_NOTES
     */
    public void setPartyNotes(String value) {
        setAttributeInternal(PARTYNOTES, value);
    }

    /**
     * Gets the attribute value for PROC_TYPE using the alias name ProcType.
     * @return the PROC_TYPE
     */
    public String getProcType() {
        return (String) getAttributeInternal(PROCTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROC_TYPE using the alias name ProcType.
     * @param value value to set the PROC_TYPE
     */
    public void setProcType(String value) {
        setAttributeInternal(PROCTYPE, value);
    }

    /**
     * Gets the attribute value for REG_NUM using the alias name RegNum.
     * @return the REG_NUM
     */
    public String getRegNum() {
        return (String) getAttributeInternal(REGNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for REG_NUM using the alias name RegNum.
     * @param value value to set the REG_NUM
     */
    public void setRegNum(String value) {
        setAttributeInternal(REGNUM, value);
    }

    /**
     * Gets the attribute value for REG_STATUS using the alias name RegStatus.
     * @return the REG_STATUS
     */
    public String getRegStatus() {
        return (String) getAttributeInternal(REGSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for REG_STATUS using the alias name RegStatus.
     * @param value value to set the REG_STATUS
     */
    public void setRegStatus(String value) {
        setAttributeInternal(REGSTATUS, value);
    }

    /**
     * Gets the attribute value for REGISTRATION_ID using the alias name RegistrationId.
     * @return the REGISTRATION_ID
     */
    public Number getRegistrationId() {
        return (Number) getAttributeInternal(REGISTRATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for REGISTRATION_ID using the alias name RegistrationId.
     * @param value value to set the REGISTRATION_ID
     */
    public void setRegistrationId(Number value) {
        setAttributeInternal(REGISTRATIONID, value);
    }

    /**
     * Gets the attribute value for REQUESTED_BY using the alias name RequestedBy.
     * @return the REQUESTED_BY
     */
    public Number getRequestedBy() {
        return (Number) getAttributeInternal(REQUESTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUESTED_BY using the alias name RequestedBy.
     * @param value value to set the REQUESTED_BY
     */
    public void setRequestedBy(Number value) {
        setAttributeInternal(REQUESTEDBY, value);
    }

    /**
     * Gets the attribute value for SHIPING_ID using the alias name ShipingId.
     * @return the SHIPING_ID
     */
    public Number getShipingId() {
        return (Number) getAttributeInternal(SHIPINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPING_ID using the alias name ShipingId.
     * @param value value to set the SHIPING_ID
     */
    public void setShipingId(Number value) {
        setAttributeInternal(SHIPINGID, value);
    }

    /**
     * Gets the attribute value for TOTAL_PFI_AMT using the alias name TotalPfiAmt.
     * @return the TOTAL_PFI_AMT
     */
    public Number getTotalPfiAmt() {
        return (Number) getAttributeInternal(TOTALPFIAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_PFI_AMT using the alias name TotalPfiAmt.
     * @param value value to set the TOTAL_PFI_AMT
     */
    public void setTotalPfiAmt(Number value) {
        setAttributeInternal(TOTALPFIAMT, value);
    }

    /**
     * Gets the attribute value for TOTAL_USD_AMT using the alias name TotalUsdAmt.
     * @return the TOTAL_USD_AMT
     */
    public Number getTotalUsdAmt() {
        return (Number) getAttributeInternal(TOTALUSDAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_USD_AMT using the alias name TotalUsdAmt.
     * @param value value to set the TOTAL_USD_AMT
     */
    public void setTotalUsdAmt(Number value) {
        setAttributeInternal(TOTALUSDAMT, value);
    }

    /**
     * Gets the attribute value for URGENCY using the alias name Urgency.
     * @return the URGENCY
     */
    public String getUrgency() {
        return (String) getAttributeInternal(URGENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for URGENCY using the alias name Urgency.
     * @param value value to set the URGENCY
     */
    public void setUrgency(String value) {
        setAttributeInternal(URGENCY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpadtedName.
     * @return the LastUpadtedName
     */
    public String getLastUpadtedName() {
        return (String) getAttributeInternal(LASTUPADTEDNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpadtedName.
     * @param value value to set the  LastUpadtedName
     */
    public void setLastUpadtedName(String value) {
        setAttributeInternal(LASTUPADTEDNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedByName.
     * @return the CreatedByName
     */
    public String getCreatedByName() {
        return (String) getAttributeInternal(CREATEDBYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedByName.
     * @param value value to set the  CreatedByName
     */
    public void setCreatedByName(String value) {
        setAttributeInternal(CREATEDBYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ConsigneeName.
     * @return the ConsigneeName
     */
    public String getConsigneeName() {
        return (String) getAttributeInternal(CONSIGNEENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ConsigneeName.
     * @param value value to set the  ConsigneeName
     */
    public void setConsigneeName(String value) {
        setAttributeInternal(CONSIGNEENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShippingName.
     * @return the ShippingName
     */
    public String getShippingName() {
        return (String) getAttributeInternal(SHIPPINGNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShippingName.
     * @param value value to set the  ShippingName
     */
    public void setShippingName(String value) {
        setAttributeInternal(SHIPPINGNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RequestedByName.
     * @return the RequestedByName
     */
    public String getRequestedByName() {
        return (String) getAttributeInternal(REQUESTEDBYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RequestedByName.
     * @param value value to set the  RequestedByName
     */
    public void setRequestedByName(String value) {
        setAttributeInternal(REQUESTEDBYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DepartmentName.
     * @return the DepartmentName
     */
    public String getDepartmentName() {
        return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentName.
     * @param value value to set the  DepartmentName
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RegistrationLinesVO.
     */
    public RowIterator getRegistrationLinesVO() {
        return (RowIterator)getAttributeInternal(REGISTRATIONLINESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ItemDetailsVO.
     */
    public RowIterator getItemDetailsVO() {
        return (RowIterator)getAttributeInternal(ITEMDETAILSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EmployeesVO1.
     */
    public RowSet getEmployeesVO1() {
        return (RowSet)getAttributeInternal(EMPLOYEESVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * Sample exportable method.
     */
    public void sampleRegistrationVORowImplExportable() {
    }

    /**
     * Sample exportable method.
     */
    public void sampleRegistrationVORowImplExportable2(String testParam1) {
    }
}
